# Generated by Django 6.0.5 on 2026-05-23 10:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_parent_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.student_photo_upload_to),
        ),
    ]
